language: node_js

node_js:
- '12'

install:
- npm install

script:
- npm run build-all

deploy:
  provider: heroku
  api_key:
    secure: fAs7h230eEDk9sXV+G/QLqncOEtqQJ5kwtscvg7EqiFtJzPEzH/pCzFEGn6lGFsLanV2s5Hzi6pah6RkMG80Pyxh/k2kuj7nxDMEmF9ooqrbSy5cIqthLCrnuKAxMzYykY+8q3dQDFG+KzEzc+1vbtCl9ahBYQRiX+n6BQaPQqAhMvk4McqfiveqagV106TRwt6x//zIrCvAX7Gwha3XepXW0Ytf8fD/eTNTVOPgRFh1j/SevEybKLjYiNxHFpm5oMF8RB0Gj/RPkt1AKJvmnLlJ43e08ZImCCW2jb+dQkZfvpu4D2tJJYZpu2G0vozci2SZI5qO0pEy9jjms5AFbjF9qRJJT+Cq8tzHFkKabRdtQNb0fcSYZ9FQa9lof6PU92m5Uwudbe5HgXA2Agf5toqvStYCFyLMvMX1gOLdztoZ/KBAlvjomi9VJbD0qFNGtb9XEhK/IY9jk4yokIWThy2SaodmjAQ1POl3eaoUedwepA5VFcMt/XHXGysuk5zvQAlZ9i43h3JON2TbZcgev8Uj/V9AQ7ANQby14iITcZsYLjTYETz98QzVkSmVd1Pbb/OGFoQVRAImKn2KNlliGdSKEmDkN7iFz9evmLk4usp/ZHl6lwIbIuh0I6ASZrFBFJrVxueFJc2IkkRWkodqYvwCCFut+o+fi0Pu496F5iw=
  app: prototype-inheritance
  on:
    repo: MayMoonsley/inheritance
    branch: master
